name: nova
build:
  steps:
    - pip install -r requirements.txt

run:
  cmd: uvicorn main:app --host 0.0.0.0 --port 8080
  healthcheck:
    http_path: /
    interval: 10s
    timeout: 5s
    retries: 3
