name: nova
builder: docker
dockerfile: Dockerfile

ports:
  - port: 8000
    protocol: http
    public: true

routes:
  - type: http
    path: /
    destination:
      port: 8000

env:
  OPENROUTER_API_KEY: "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"
